"""Миграция для бд из рабочей версии проекта

Revision ID: 233925ed233c
Revises: f301bf20aba3
Create Date: 2024-02-06 09:49:09.010506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233925ed233c'
down_revision = 'f301bf20aba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('alt', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.Column('setting', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    op.drop_table('settings')
    op.drop_table('photos')
    # ### end Alembic commands ###
