"""empty message

Revision ID: d85b306f99ec
Revises: 233925ed233c
Create Date: 2024-03-20 22:01:56.986694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd85b306f99ec'
down_revision = '233925ed233c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_name', sa.String(length=10), nullable=True),
    sa.Column('tour_id', sa.Integer(), nullable=True),
    sa.Column('name1', sa.String(length=25), nullable=True),
    sa.Column('name2', sa.String(length=25), nullable=True),
    sa.Column('goal1', sa.Integer(), nullable=True),
    sa.Column('goal2', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('goal1', sa.Integer(), nullable=True),
    sa.Column('goal2', sa.Integer(), nullable=True),
    sa.Column('dt_predict', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('alt',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.alter_column('alt',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    op.drop_table('predicts')
    op.drop_table('matches')
    op.drop_table('tours')
    op.drop_table('seasons')
    # ### end Alembic commands ###
